startRedisContainer:
	docker start redis-stack-server

startRedis:
	docker exec -it redis-stack-server redis-cli

install_tcpdump:
	sudo apt-get install tcpdump

install_tcpdump_in_container:
	docker exec -it <redis-container> bash
apt-get update && apt-get install tcpdump -y
tcpdump -A -i any port 6379

start_tcpdump:
	tcpdump -A -i any port 6379

stopRedisContainer:
	docker stop redis-stack-server